require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ano_modelos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AnoModelo. As you add validations to AnoModelo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AnoModelo.create! valid_attributes
      get ano_modelos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ano_modelo = AnoModelo.create! valid_attributes
      get ano_modelo_url(ano_modelo)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ano_modelo_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ano_modelo = AnoModelo.create! valid_attributes
      get edit_ano_modelo_url(ano_modelo)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnoModelo" do
        expect {
          post ano_modelos_url, params: { ano_modelo: valid_attributes }
        }.to change(AnoModelo, :count).by(1)
      end

      it "redirects to the created ano_modelo" do
        post ano_modelos_url, params: { ano_modelo: valid_attributes }
        expect(response).to redirect_to(ano_modelo_url(AnoModelo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnoModelo" do
        expect {
          post ano_modelos_url, params: { ano_modelo: invalid_attributes }
        }.to change(AnoModelo, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post ano_modelos_url, params: { ano_modelo: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ano_modelo" do
        ano_modelo = AnoModelo.create! valid_attributes
        patch ano_modelo_url(ano_modelo), params: { ano_modelo: new_attributes }
        ano_modelo.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ano_modelo" do
        ano_modelo = AnoModelo.create! valid_attributes
        patch ano_modelo_url(ano_modelo), params: { ano_modelo: new_attributes }
        ano_modelo.reload
        expect(response).to redirect_to(ano_modelo_url(ano_modelo))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        ano_modelo = AnoModelo.create! valid_attributes
        patch ano_modelo_url(ano_modelo), params: { ano_modelo: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ano_modelo" do
      ano_modelo = AnoModelo.create! valid_attributes
      expect {
        delete ano_modelo_url(ano_modelo)
      }.to change(AnoModelo, :count).by(-1)
    end

    it "redirects to the ano_modelos list" do
      ano_modelo = AnoModelo.create! valid_attributes
      delete ano_modelo_url(ano_modelo)
      expect(response).to redirect_to(ano_modelos_url)
    end
  end
end
