require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/preco_veiculos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PrecoVeiculo. As you add validations to PrecoVeiculo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PrecoVeiculo.create! valid_attributes
      get preco_veiculos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      preco_veiculo = PrecoVeiculo.create! valid_attributes
      get preco_veiculo_url(preco_veiculo)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_preco_veiculo_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      preco_veiculo = PrecoVeiculo.create! valid_attributes
      get edit_preco_veiculo_url(preco_veiculo)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PrecoVeiculo" do
        expect {
          post preco_veiculos_url, params: { preco_veiculo: valid_attributes }
        }.to change(PrecoVeiculo, :count).by(1)
      end

      it "redirects to the created preco_veiculo" do
        post preco_veiculos_url, params: { preco_veiculo: valid_attributes }
        expect(response).to redirect_to(preco_veiculo_url(PrecoVeiculo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PrecoVeiculo" do
        expect {
          post preco_veiculos_url, params: { preco_veiculo: invalid_attributes }
        }.to change(PrecoVeiculo, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post preco_veiculos_url, params: { preco_veiculo: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested preco_veiculo" do
        preco_veiculo = PrecoVeiculo.create! valid_attributes
        patch preco_veiculo_url(preco_veiculo), params: { preco_veiculo: new_attributes }
        preco_veiculo.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the preco_veiculo" do
        preco_veiculo = PrecoVeiculo.create! valid_attributes
        patch preco_veiculo_url(preco_veiculo), params: { preco_veiculo: new_attributes }
        preco_veiculo.reload
        expect(response).to redirect_to(preco_veiculo_url(preco_veiculo))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        preco_veiculo = PrecoVeiculo.create! valid_attributes
        patch preco_veiculo_url(preco_veiculo), params: { preco_veiculo: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested preco_veiculo" do
      preco_veiculo = PrecoVeiculo.create! valid_attributes
      expect {
        delete preco_veiculo_url(preco_veiculo)
      }.to change(PrecoVeiculo, :count).by(-1)
    end

    it "redirects to the preco_veiculos list" do
      preco_veiculo = PrecoVeiculo.create! valid_attributes
      delete preco_veiculo_url(preco_veiculo)
      expect(response).to redirect_to(preco_veiculos_url)
    end
  end
end
