require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/referencia_fipes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ReferenciaFipe. As you add validations to ReferenciaFipe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReferenciaFipe.create! valid_attributes
      get referencia_fipes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      referencia_fipe = ReferenciaFipe.create! valid_attributes
      get referencia_fipe_url(referencia_fipe)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_referencia_fipe_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      referencia_fipe = ReferenciaFipe.create! valid_attributes
      get edit_referencia_fipe_url(referencia_fipe)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReferenciaFipe" do
        expect {
          post referencia_fipes_url, params: { referencia_fipe: valid_attributes }
        }.to change(ReferenciaFipe, :count).by(1)
      end

      it "redirects to the created referencia_fipe" do
        post referencia_fipes_url, params: { referencia_fipe: valid_attributes }
        expect(response).to redirect_to(referencia_fipe_url(ReferenciaFipe.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReferenciaFipe" do
        expect {
          post referencia_fipes_url, params: { referencia_fipe: invalid_attributes }
        }.to change(ReferenciaFipe, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post referencia_fipes_url, params: { referencia_fipe: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested referencia_fipe" do
        referencia_fipe = ReferenciaFipe.create! valid_attributes
        patch referencia_fipe_url(referencia_fipe), params: { referencia_fipe: new_attributes }
        referencia_fipe.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the referencia_fipe" do
        referencia_fipe = ReferenciaFipe.create! valid_attributes
        patch referencia_fipe_url(referencia_fipe), params: { referencia_fipe: new_attributes }
        referencia_fipe.reload
        expect(response).to redirect_to(referencia_fipe_url(referencia_fipe))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        referencia_fipe = ReferenciaFipe.create! valid_attributes
        patch referencia_fipe_url(referencia_fipe), params: { referencia_fipe: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested referencia_fipe" do
      referencia_fipe = ReferenciaFipe.create! valid_attributes
      expect {
        delete referencia_fipe_url(referencia_fipe)
      }.to change(ReferenciaFipe, :count).by(-1)
    end

    it "redirects to the referencia_fipes list" do
      referencia_fipe = ReferenciaFipe.create! valid_attributes
      delete referencia_fipe_url(referencia_fipe)
      expect(response).to redirect_to(referencia_fipes_url)
    end
  end
end
